### ISSUE TITLE
Nothing happens when clicking generate

### ISSUE THREAD

**Issue by meerpack** [diStyApps/VisionCrafter#12]
![image](https://github.com/diStyApps/VisionCrafter/assets/14966598/5d395518-b15c-41eb-ba8c-bbdff6cecc81)
I click generate but the only thing that happens is the "selected lora.." message. Nothing is generated. What am i missing?

**Comment by diStyApps** [comment]
Try to move the content of "VisionCrafter-main"

To 'C:\Users\Konzr\Downloads\AI\visioncrafter and not in "VisionCrafter-main" folders

So the main.py is inside 'C:\Users\Konzr\Downloads\AI\visioncrafter' and not in "VisionCrafter-main"

**Comment by meerpack** [comment]
> Try to move the content of "VisionCrafter-main"
> 
> To 'C:\Users\Konzr\Downloads\AI\visioncrafter and not in "VisionCrafter-main" folders
> 
> So the main.py is inside 'C:\Users\Konzr\Downloads\AI\visioncrafter' and not in "VisionCrafter-main"

It now gives me this error: 
![image](https://github.com/diStyApps/VisionCrafter/assets/14966598/bcd2552c-c1f5-4ad4-aa41-d7683e57fc8c)

**Comment by meerpack** [comment]
its confusing because you have a models folder inside the visioncrafter main and then another models folder inside the repos folder so im not sure which should be used.

**Comment by diStyApps** [comment]
> its confusing because you have a models folder inside the visioncrafter main and then another models folder inside the repos folder so im not sure which should be used.

To easily install VisionCrafter use SEAIT which will install it for you:
https://github.com/diStyApps/seait
https://civitai.com/models/27574/super-easy-ai-installer-tool

**Comment by meerpack** [comment]
> > its confusing because you have a models folder inside the visioncrafter main and then another models folder inside the repos folder so im not sure which should be used.
> 
> To easily install VisionCrafter use SEAIT which will install it for you: https://github.com/diStyApps/seait https://civitai.com/models/27574/super-easy-ai-installer-tool

I went through the entire SEAIT installation from the beginning and it is still giving me the same error: 
![image](https://github.com/diStyApps/VisionCrafter/assets/14966598/2766a23b-bfb2-4aeb-acf6-a825a89b1226)

**Comment by AsaTyr2018** [comment]
Tool Tip No1 with all AI Generation Units.
Check for the correct Python version. Had similar issues.

This Version works best:
![grafik](https://github.com/diStyApps/VisionCrafter/assets/43162495/e516470f-3b56-478c-937b-270977e6d826)

Also Update your Pip
![grafik](https://github.com/diStyApps/VisionCrafter/assets/43162495/72d080ab-1e15-49e1-bf64-1f6b56a8df64)

23.0.1 has some compatibility issues with newer repos and doesn´t install "clean".
Things like this can happen:
![grafik](https://github.com/diStyApps/VisionCrafter/assets/43162495/dcda5550-b2b7-4bf1-811d-186879a2d622)

**Comment by AsaTyr2018** [comment]
Please Start a powershell and queue this command and past me the output:
Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like 'Python *' } | Select-Object Name, Version

**Comment by AsaTyr2018** [comment]
Ticket Closed. No Reply.
