### ISSUE TITLE
[Issue] Python was not found

### ISSUE THREAD

**Issue by smokelore** [diStyApps/VisionCrafter#14]
![image](https://github.com/diStyApps/VisionCrafter/assets/1188899/18d09533-91cd-4ad4-9ed2-c5099f905168)

Just installed and tried to run VisionCrafter and received this error:
```
The system cannot find the path specified.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
The system cannot find the path specified.
Press any key to continue . . .
```

Just wanted to flag that the ReadMe of this repo does not specify Python as a prerequisite and the installer doesn't install it.

What is the preferred version of Python to install for this application?

Thanks!

**Comment by diStyApps** [comment]
Well It is a python project, but i will try to make it more clear.
To easily install use SEAIT which will install python for you and VisionCrafter:
https://github.com/diStyApps/seait
https://civitai.com/models/27574/super-easy-ai-installer-tool

**Comment by smokelore** [comment]
Good to know, thanks.

**Comment by AsaTyr2018** [comment]
Purely from what i learned so far. This version is the best for Use with several AI types.
![grafik](https://github.com/diStyApps/VisionCrafter/assets/43162495/5dbed12c-2257-4aa9-a84c-7e0ae719dabc)
Remove all other Python versions and just install this. as long you are no AI Engineer you should have no problem with it =)

**Comment by AsaTyr2018** [comment]
> Good to know, thanks.

Any Updates in this Matter?

**Comment by smokelore** [comment]
I installed Python 3.10 via Chocolatey and that resolved it. Thanks.

**Comment by smokelore** [comment]
I installed Python 3.10 via Chocolatey and that resolved it. Thanks.
