### ISSUE TITLE
[Feature Request] Stop/Interupt Button

### ISSUE THREAD

**Issue by AsaTyr2018** [diStyApps/VisionCrafter#15]
Hey there.
Is it possible to Include an "Stop" or "Interupt" button to stop current generation?

Like if you found an error in the Prompts and you just started a batch proccessing. Currently i can just kill the whole Program and lose the current Prompting settings.

**Comment by diStyApps** [comment]
Added.

**Comment by AsaTyr2018** [comment]
> 

You are Awsome! I love this Tool. Not as Functional as A1111. but in case of Video/Animation Creation lightyears ahead! 

Really a great job you did there =) 

I will Update and test it as soon as my current batch is throu and give a feedback.

**Comment by AsaTyr2018** [comment]
I have to tell. The Interrupt works better then aspected and instantly o.o 

Thanks a lot =D This makes things easyer!
