### ISSUE TITLE
[Feature Request or Bug] - Model and Lora Recursive Folder scan/Rescan

### ISSUE THREAD

**Issue by AsaTyr2018** [diStyApps/VisionCrafter#16]
Hello there,

I'm currently facing a situation that I'm unsure whether it's a bug or not within the current scope.

Current Situation:
The Model and Lora Changer currently only scans the main folder but ignores subfolders. Since I have a large number of Loras and Models, I've sorted them into a folder structure (e.g., Anime, Realistic, Landscape, etc.). However, whenever there's a change, I'm required to select the folder again (Set Models Folder/Set Lora Folder).

Proposed Improvement:
To make the process more efficient, I suggest implementing a recursive scan that can go through subfolders. Additionally, it would be helpful to have a separate window for a better overview of the files. Moreover, adding a "Rescan" or "Update" button next to the existing "Set" buttons would enable us to rescan the current Model Directory easily.

By making these enhancements, the user experience would be greatly improved, and managing the folders would become much more convenient.

**Comment by diStyApps** [comment]
I agree i also use it, will be implemented in the future updates.
Thank you very much for your suggestions.
