### ISSUE TITLE
[Question] A matching Triton is not available, some optimizations will not be enabled.

### ISSUE THREAD

**Issue by trxsudo** [diStyApps/VisionCrafter#17]
what does this mean? what should I do? the generation time seems extremely slow. about 30 mins for a 2 second video default setting.

my gpu is 3080ti 16gb vram mobile version.  running stable diffusion quite smoothly. windows 11. 32g ram

command line shows this:
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'

**Comment by AsaTyr2018** [comment]
Can you give some more Informations like Used OS, Version, GPU etc....?

Triton ist an Accelerator. it can boost the creation. 
![grafik](https://github.com/diStyApps/VisionCrafter/assets/43162495/2131f2a2-68a0-46b0-a150-3c1f208345d4)


But if you currently need 30 Minutes for 2 seconds. i would perferable advice a new gpu.

**Comment by diStyApps** [comment]
It is not available for windows or at least no in an easy way if i remember currently, on 3090 takes about 25 to 30 seconds to generate 2 sec on default settings.

**Comment by trxsudo** [comment]
> Can you give some more Informations like Used OS, Version, GPU etc....?
> 
> Triton ist an Accelerator. it can boost the creation. ![grafik](https://user-images.githubusercontent.com/43162495/259163466-2131f2a2-68a0-46b0-a150-3c1f208345d4.png)
> 
> But if you currently need 30 Minutes for 2 seconds. i would perferable advice a new gpu.

my gpu is 3080ti 16gb vram mobile version.  32gb ram , windows 11. running stable diffusion quite smoothly.

**Comment by AsaTyr2018** [comment]
> > Can you give some more Informations like Used OS, Version, GPU etc....?
> > Triton ist an Accelerator. it can boost the creation. ![grafik](https://user-images.githubusercontent.com/43162495/259163466-2131f2a2-68a0-46b0-a150-3c1f208345d4.png)
> > But if you currently need 30 Minutes for 2 seconds. i would perferable advice a new gpu.
> 
> my gpu is 3080ti 16gb vram mobile version. 32gb ram , windows 11. running stable diffusion quite smoothly.

Comparing Stable Diffusion to Visioncrafter is akin to comparing a "Volkswagen" and a "Porsche."

SD is mainly for creating single images. VC for itself creates mass images and combine them to a video file (or gif).
The Requirements are definitly different.

Mobile Cards are mostly reduced in performance due to ther nature "Mobility". Meaning not Producing much heat.
See: [https://www.makeuseof.com/desktop-vs-laptop-gpu-what-is-the-difference/](https://www.makeuseof.com/desktop-vs-laptop-gpu-what-is-the-difference/)

I did some research on triton. It seams only a few people managed to install it and gave out some guides that no one could really use. 
i tried myself and the original pip install doesn´t even work. Looks like they take off the windows binarys. So as long as you don´t switch over to linux. no triton i guess.

**Comment by B34STW4RS** [comment]
Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:

pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118

Currently ignoring it for visioncrafter though...

**Comment by AsaTyr2018** [comment]
> Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> 
> pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> 
> Currently ignoring it for visioncrafter though...

Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. 
But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.

**Comment by B34STW4RS** [comment]
> > Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> > pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> > Currently ignoring it for visioncrafter though...
> 
> Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.

Oh no I used it for inference, for some reason my 4090 only really performed well with that release for what I was doing. Speed gain was about 25%. But I don't think that will translate well to visioncrafter, don't have time to dig through it all right now.

**Comment by AsaTyr2018** [comment]
> > > Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> > > pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> > > Currently ignoring it for visioncrafter though...
> > 
> > 
> > Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.
> 
> Oh no I used it for inference, for some reason my 4090 only really performed well with that release for what I was doing. Speed gain was about 25%. But I don't think that will translate well to visioncrafter, don't have time to dig through it all right now.

would be great to get some actual results or a working guide.
I don´t need it. got enough gpu power to create videos in bulk xD (gpu cluster ~128gb vram etc.... yes i´m a crazy basement dweller xD)

**Comment by B34STW4RS** [comment]
> > > > Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> > > > pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> > > > Currently ignoring it for visioncrafter though...
> > > 
> > > 
> > > Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.
> > 
> > 
> > Oh no I used it for inference, for some reason my 4090 only really performed well with that release for what I was doing. Speed gain was about 25%. But I don't think that will translate well to visioncrafter, don't have time to dig through it all right now.
> 
> would be great to get some actual results or a working guide. I don´t need it. got enough gpu power to create videos in bulk xD (gpu cluster ~128gb vram etc.... yes i´m a crazy basement dweller xD)

Maybe sometime soon, I only found time to read the AnimateDiff paper this week, even though its been out for a month, and still haven't had time to actually dig through the original repo. Not to mention the hundred other papers on my must read list...

**Comment by AsaTyr2018** [comment]
> > > > > Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> > > > > pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> > > > > Currently ignoring it for visioncrafter though...
> > > > 
> > > > 
> > > > Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.
> > > 
> > > 
> > > Oh no I used it for inference, for some reason my 4090 only really performed well with that release for what I was doing. Speed gain was about 25%. But I don't think that will translate well to visioncrafter, don't have time to dig through it all right now.
> > 
> > 
> > would be great to get some actual results or a working guide. I don´t need it. got enough gpu power to create videos in bulk xD (gpu cluster ~128gb vram etc.... yes i´m a crazy basement dweller xD)
> 
> Maybe sometime soon, I only found time to read the AnimateDiff paper this week, even though its been out for a month, and still haven't had time to actually dig through the original repo. Not to mention the hundred other papers on my must read list...

can you post some of that papers? i got a lot of free time atm. (recovering from an accident) and i need something to do xD

**Comment by B34STW4RS** [comment]
> > > > > > Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> > > > > > pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> > > > > > Currently ignoring it for visioncrafter though...
> > > > > 
> > > > > 
> > > > > Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.
> > > > 
> > > > 
> > > > Oh no I used it for inference, for some reason my 4090 only really performed well with that release for what I was doing. Speed gain was about 25%. But I don't think that will translate well to visioncrafter, don't have time to dig through it all right now.
> > > 
> > > 
> > > would be great to get some actual results or a working guide. I don´t need it. got enough gpu power to create videos in bulk xD (gpu cluster ~128gb vram etc.... yes i´m a crazy basement dweller xD)
> > 
> > 
> > Maybe sometime soon, I only found time to read the AnimateDiff paper this week, even though its been out for a month, and still haven't had time to actually dig through the original repo. Not to mention the hundred other papers on my must read list...
> 
> can you post some of that papers? i got a lot of free time atm. (recovering from an accident) and i need something to do xD

Sure here are some interesting and relevant ones:

https://arxiv.org/pdf/2104.14631.pdf
https://arxiv.org/pdf/2302.03011.pdf
https://arxiv.org/pdf/2303.13439v1.pdf
https://arxiv.org/pdf/2307.04725.pdf

**Comment by AsaTyr2018** [comment]
> 



> > > > > > > Dunno if this is relevant, but for another project I was using this on windows with a definite speed boost:
> > > > > > > pip install torch==2.0.1+cu118 torchvision pytorch-triton --extra-index-url https://download.pytorch.org/whl/cu118
> > > > > > > Currently ignoring it for visioncrafter though...
> > > > > > 
> > > > > > 
> > > > > > Yes i found this one too. Its Primary Usage is for Model Training. Duno if its works actively for content creation itself. But regardless. On a Mobile Cards it would be a waste of storage. The Benifit wouldn´t be that great.
> > > > > 
> > > > > 
> > > > > Oh no I used it for inference, for some reason my 4090 only really performed well with that release for what I was doing. Speed gain was about 25%. But I don't think that will translate well to visioncrafter, don't have time to dig through it all right now.
> > > > 
> > > > 
> > > > would be great to get some actual results or a working guide. I don´t need it. got enough gpu power to create videos in bulk xD (gpu cluster ~128gb vram etc.... yes i´m a crazy basement dweller xD)
> > > 
> > > 
> > > Maybe sometime soon, I only found time to read the AnimateDiff paper this week, even though its been out for a month, and still haven't had time to actually dig through the original repo. Not to mention the hundred other papers on my must read list...
> > 
> > 
> > can you post some of that papers? i got a lot of free time atm. (recovering from an accident) and i need something to do xD
> 
> Sure here are some interesting and relevant ones:
> 
> https://arxiv.org/pdf/2104.14631.pdf https://arxiv.org/pdf/2302.03011.pdf https://arxiv.org/pdf/2303.13439v1.pdf https://arxiv.org/pdf/2307.04725.pdf

ok thats hard stuff. i like hard stuff xD Thank you.

**Comment by rbychn** [comment]
got the same error, any quick fixes?

**Comment by AsaTyr2018** [comment]
> got the same error, any quick fixes?

Its less an Error. More a "Not Easy to Implement". We still checking.

**Comment by jags111** [comment]
I am getting this error and then it says out of cuda memory error when i am able to run animate diff easy on the comfyUI and other platforms with ease and also more than 400 frames. I thought this would be better , but seeing errors cannot continue.

**Comment by AsaTyr2018** [comment]
> I am getting this error and then it says out of cuda memory error when i am able to run animate diff easy on the comfyUI and other platforms with ease and also more than 400 frames. I thought this would be better , but seeing errors cannot continue.

Its on the List for Improvements. Currently there is no quickfix we can offer.
