### ISSUE TITLE
[Feature Request] API Support

### ISSUE THREAD

**Issue by rbychn** [diStyApps/VisionCrafter#2]
Would be great to have some endpoints that we can hit similar to what we can in [A1111 SD](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API), such that we can do batch and other custom generations as per our requirements.

**Comment by rbychn** [comment]
I want to use it with clip/deepbooru so that it can automatically generate prompts using interrogate and generate animations for each of the images that I have in a folder. Doing this manually for every single image would be time-consuming if there are many init images. Just want to find out the best settings and then let it autogenerate.

**Comment by rbychn** [comment]
@AsaTyr2018 why was this closed? why were a lot of issues closed?

**Comment by AsaTyr2018** [comment]
@rbychn i added the current enhancements to the backlog since disty is currently overwhelmed with projects. 
so "closed" is the wrong term here =)
No worry we don´t forget this case and all the others.
