### ISSUE TITLE
Model folder Settings are incorrect

### ISSUE THREAD

**Issue by ZhengXuan1978** [diStyApps/VisionCrafter#20]
The folders Set by the "Set models folder" and "Set lora folder" buttons coincide and cannot be set separately, resulting in the model cannot be invoked normally. Please correct this error

**Comment by AsaTyr2018** [comment]
checked it on my install and its working. what version do you use?

Overall. They will be reworked:
#https://github.com/diStyApps/VisionCrafter/issues/16

**Comment by ZhengXuan1978** [comment]
i use v0.0.5



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 11, 2023 00:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [diStyApps/VisionCrafter] Model folder Settings are incorrect(Issue #20)




 
checked it on my install and its working. what version do you use?
 
Overall. They will be reworked:
 ##16

**Comment by AsaTyr2018** [comment]
> i use v0.0.5
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Aug 11, 2023 00:13 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [diStyApps/VisionCrafter] Model folder Settings are incorrect(Issue #20) checked it on my install and its working. what version do you use? Overall. They will be reworked: ##16 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Try removing it and Reinstall. maby some junk didn´t install correctly. 
tested it double on my pc and my server. both seams be without problems. 

any errors in the console log when you try to change the model/lora?

**Comment by ZhengXuan1978** [comment]
thanks you，I'll try to reinstall the program



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 11, 2023 00:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [diStyApps/VisionCrafter] Model folder Settings are incorrect(Issue #20)




  
i use v0.0.5
 …
 ---Original--- From: @.&gt; Date: Fri, Aug 11, 2023 00:13 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [diStyApps/VisionCrafter] Model folder Settings are incorrect(Issue #20) checked it on my install and its working. what version do you use? Overall. They will be reworked: ##16 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Try removing it and Reinstall. maby some junk didn´t install correctly.
 tested it double on my pc and my server. both seams be without problems.
 
any errors in the console log when you try to change the model/lora?

**Comment by AsaTyr2018** [comment]
> thanks you，I'll try to reinstall the program
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Aug 11, 2023 00:21 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [diStyApps/VisionCrafter] Model folder Settings are incorrect(Issue #20) i use v0.0.5 … ---Original--- From: @.&gt; Date: Fri, Aug 11, 2023 00:13 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [diStyApps/VisionCrafter] Model folder Settings are incorrect(Issue #20) checked it on my install and its working. what version do you use? Overall. They will be reworked: ##16 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; Try removing it and Reinstall. maby some junk didn´t install correctly. tested it double on my pc and my server. both seams be without problems. any errors in the console log when you try to change the model/lora? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Keep me Updated and Post a console Output after you change the model/lora. Maby there is something to follow up.

**Comment by ZhengXuan1978** [comment]
The problem was solved after reinstallation
