### ISSUE TITLE
[Feature Request]:  Resize UI, change font size, move window, resize window, etc.

### ISSUE THREAD

**Issue by Ainaemaet** [diStyApps/VisionCrafter#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

I'm loving the program so far and very excited to see how it develops. 
Unfortunately the one _glaring_ issue I have with it, is that it just give me a rather obtrusive UI that is just stuck full screen with no ability to resize either any of the elements, or the window itself. 

For this reason alone I have been choosing to use other programs, as it makes working with anything else on the computer a pain in the behind - and it just seems so very odd that it would be made that way. 

This day and age we all multi-task on our PC's, and I think the ability to resize our program windows so we can dock them in various parts of the screen, or shrink them so we can use the rest of our screen real-estate for other purposes is absolutely essential. 

### Description

Pretty basic really. If the program is going to remain using the current UI frontend, being able to change various aspects of the UI would be a huge boon to it's adoption I believe. 

In specifics, being able to change the font size (or even the font itself), as well as the ability to change the window size with the UI elements dynamically adjusting for it would be optimal. 

Somewhat less necessary, but something that would be really cool - would be the ability to re-arrange the UI elements the way we want them - but certainly not a deal breaker!

As far as the resizing font ability and moving/resizing the window goes though, quite honestly as much as I love this program, if it remained the way it currently is I don't think I would be able to stay with it very long as I am using a 48" 4k monitor that I sit a good 3-4 feet away from and many of the elements text demands that I either scooch myself forwards or that I have to use Windows Zoom feature to read everything easily. 

I actually put off testing it for sometime in part because having the UI taking up my entire screen was more than a little frustrating. :)

**Comment by AsaTyr2018** [comment]
Good day, 
as far i know this gui will change once the majority of features has been determed. And ofcause once @diStyApps find the time to change it. so please bear in mind its just 1 person that currently work on it =)

About the resizing. What do you mean directly? Cause i can resize and dock the installer tool perfectly
![grafik](https://github.com/diStyApps/VisionCrafter/assets/43162495/e4db0d8a-6f78-418c-a700-aa04a6620464)

**Comment by Ainaemaet** [comment]
Strange, I thought I commented on this already. 

Not talking about the installer, I'm talking about the VisionCrafter GUI.
