### ISSUE TITLE
[Feature Request]: Finetuned Motion Modules

### ISSUE THREAD

**Issue by B34STW4RS** [diStyApps/VisionCrafter#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

Implement loading finetuned motion modules.

### Description

Implement loading finetuned motion modules from a dropdown like other models. Now that trainer code has been released I am working with other like minded individuals to train new motion modules.

**Comment by diStyApps** [comment]
Thank you very much, ill try it , i am aware they released the training scripts.
Few weeks ago I also did some training with the original project https://github.com/showlab/Tune-A-Video, it worked nice.

**Comment by diStyApps** [comment]
added
