### ISSUE TITLE
[Feature Request]: Implementing Controlnet Features? 

### ISSUE THREAD

**Issue by Maki9009** [diStyApps/VisionCrafter#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Summary

Its possible to implement controlnets to animatediff to control the animation, https://twitter.com/toyxyz3/status/1695849125663973561?s=20

### Description

if it would be nice to have a video processors that uses ffmpeg to cut a portion of a video to produce, an animation based on controlnet openpose and tilenet upscale would be great also, 

https://twitter.com/toyxyz3/status/1695761541226955081?s=20

### Additional information

it would be even cool to make longer videos to cut 24frames and process them and stitch them to a very long video or gif

**Comment by AsaTyr2018** [comment]
Sounds like a good thing to include. But it will take some time i guess. 
Disty is currently short on time. But i add it to the Dashboard to review. 

If you have more Details and Informations to add. Please do.

**Comment by filliptm** [comment]
bump, def need control nets!

**Comment by AsaTyr2018** [comment]
> bump, def need control nets!

its possible that its comes in once the stand alone interface (Webinterface) comes in action. The current native Python Interface in plan to change.
