### ISSUE TITLE
Error and quit after end of movie prosses

### ISSUE THREAD

**Issue by ShmuelRonen** [diStyApps/VisionCrafter#3]
In my second experience, after it finished creating the video and before playing it and creating the music, an error occurred and the software closed. Maybe it's a matter of memory. I used a resolution of 768 x 512 and there may not have been enough memory to continue.

I have a computer with 32 GB memory. and an RTX 3090 graphics card

100%|██████████████████████████████████████████████████████████████████████████████| 120/120 [03:03<00:00,  1.53s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 48/48 [00:07<00:00,  6.43it/s]
[libx264 @ 000002a81579d640] -qscale is ignored, -crf is recommended.
[libx264 @ 0000025ab1c3d5c0] -qscale is ignored, -crf is recommended.
Press any key to continue . . .

**Comment by diStyApps** [comment]
Can you also copy the output in the in app terminal, and without music its working?
And in the output folder it created the videos?

**Comment by ShmuelRonen** [comment]
How to disable music production?

**Comment by diStyApps** [comment]
Uncheck Add to video:

![Screenshot 2023-08-02 130208](https://github.com/diStyApps/VisionCrafter/assets/3084832/75f955e4-65aa-4632-9447-a7db9997f525)

**Comment by ShmuelRonen** [comment]
Mabe; Add to video = Disable music

**Comment by ShmuelRonen** [comment]
> Can you also copy the output in the in app terminal, and without music its working? And in the output folder it created the videos?

I  made a number of video productions without sound at a resolution of 768 x 512 without any problems.

**Comment by AsaTyr2018** [comment]
> > Can you also copy the output in the in app terminal, and without music its working? And in the output folder it created the videos?
> 
> I made a number of video productions without sound at a resolution of 768 x 512 without any problems.

check your python version. i had an issue with the latest version of python and audio generating ai´s. 
Best Version for allrounder ai´s so far:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49)

**Comment by AsaTyr2018** [comment]
No Reaction for 2 weeks. If the Issue still exist, please open a new Ticket.
