### ISSUE TITLE
[Feature Request] option to select styles from the styles.csv file

### ISSUE THREAD

**Issue by ShmuelRonen** [diStyApps/VisionCrafter#4]
Ability to choose styles will enrich the creation of the software. I would appreciate it if you could check the possibility of doing so.

**Comment by ShmuelRonen** [comment]
I did an experiment of manually entering styles when {the prompt} I put in parentheses. and the negative prompt there in the negative line and it works great.
The whole issue is to create the automatic mechanism for this to happen when choosing a speciphic style.
![style1](https://github.com/diStyApps/VisionCrafter/assets/80190186/3b55cdd5-f9d1-4e54-9f85-ae284a2ad931)
![style 2](https://github.com/diStyApps/VisionCrafter/assets/80190186/04823143-7fd1-42e7-96c2-0c8d349880d9)

**Comment by AsaTyr2018** [comment]
In A1111 was this Feature called "Prompts from file". 
You need a feature to automate or setup a batch script for multiple styles/Prompts?
Correct me if i´m wrong. 

For Image Generation is this great. but for Videos? Wouldn´t it take a very long time and a lot of ressources?

Just Currious ^^
