### ISSUE TITLE
[Feature Request] Options for saving frames as an image sequence

### ISSUE THREAD

**Issue by toyxyz** [diStyApps/VisionCrafter#5]
Currently, when I generate a video, it is saved as a GIF and MP4. If I do additional img2img on top of that, I need to convert these files back to image sequences. It would be very helpful if there was an option to save as an image sequence. Thanks!
![image](https://github.com/diStyApps/VisionCrafter/assets/8006000/db0dcf69-5e2a-438d-ae24-6806fbbb9bed)

**Comment by diStyApps** [comment]
I will add it.

**Comment by diStyApps** [comment]
Added.
